POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "Eka",
    "author": "Viljami Virolainen",
    "url": "google.fi",
    "likes": 5
}

GET http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json